-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('REPORT_STATUS_CHANGED', 'REPORT_REJECTED', 'CHALLENGE_COMPLETED', 'CHALLENGE_REMINDER', 'XP_EARNED', 'BADGE_EARNED', 'NEW_REPORT_ADMIN') NOT NULL;

-- AlterTable
ALTER TABLE `Report` ADD COLUMN `resolutionNote` TEXT NULL,
    ADD COLUMN `resolutionPhotoUrl` VARCHAR(191) NULL,
    ADD COLUMN `resolvedAt` DATETIME(3) NULL;
